version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9  # Wybierz odpowiednią wersję Pythona
    working_directory: ~/calculator  # Katalog roboczy dla projektu

jobs:
  test:
    executor: python-executor
    steps:
      - checkout  # Sprawdzenie repozytorium
      - run:
          name: Install pytest
          command: |
            python -m venv venv  # Tworzymy wirtualne środowisko
            . venv/bin/activate
            pip install --upgrade pip  # Uaktualniamy pip
            pip install pytest  # Instalujemy pytest bezpośrednio
      - run:
          name: Run tests with pytest
          command: |
            . venv/bin/activate
            pytest calculator/test_calculator.py  # Uruchamiamy testy z pytest

workflows:
  version: 2
  test:
    jobs:
      - test
