version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9  # Wybierz odpowiednią wersję Pythona
    working_directory: ~/calculator  # Katalog roboczy dla projektu

jobs:
  test:
    executor: python-executor
    steps:
      - checkout  # Sprawdzenie repozytorium
      - run:
          name: Install dependencies
          command: |
            python -m venv venv  # Tworzymy wirtualne środowisko
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt  # Instalujemy zależności z requirements.txt
      - run:
          name: Run tests with pytest
          command: |
            . venv/bin/activate
            pytest tests/test_calculator.py  # Uruchamiamy testy za pomocą pytest

workflows:
  version: 2
  test:
    jobs:
      - test
